# Generated by Django 2.2.1 on 2019-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('publication_year', models.PositiveIntegerField()),
                ('isbn', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True)),
            ],
        ),
    ]
